use crate::daw::model::{ArrangementTrack, Clip};
use std::fs;
use std::path::Path;

pub fn generate_lua_script(
        tracks: &Vec<ArrangementTrack>,
        clips: &Vec<Clip>,
        mixer_tracks: &Vec<crate::daw::state::MixerTrackData>,
        plugins: &Vec<crate::daw::state::PluginInstanceData>,
        project_path: &Path,
) -> String {
        let mut script = String::new();
        script.push_str("-- MyDAW Project File\n");
        script.push_str("-- Generated by MyDAW Serializer\n\n");

        script.push_str("project {\n");
        script.push_str("  name = \"Untitled Project\",\n");
        script.push_str("  bpm = 120.0,\n");
        script.push_str("  sample_rate = 44100\n");
        script.push_str("}\n\n");

        for plugin in plugins {
                script.push_str(&format!(
            "plugin {{\n  id = \"{}\",\n  name = \"{}\",\n  label = \"{}\",\n  routing_track = {},\n  format = \"Internal\"\n}}\n\n",
            plugin.id, plugin.name, plugin.label, plugin.routing_track_index
        ));
        }

        for track in tracks {
                script.push_str(&format!(
                        "track {{\n  id = {},\n  name = \"{}\",\n  color = \"{}\",\n  target_mixer = {}\n}}\n\n",
                        track.id, track.name, track.color, track.target_mixer_track_id
                ));
        }

        for clip in clips {
                let mut audio_path_str = String::new();
                if let crate::daw::model::ClipContent::Audio { path: audio_src } = &clip.content {
                        let assets_dir = project_path.join("assets");
                        if !assets_dir.exists() {
                                fs::create_dir_all(&assets_dir).ok();
                        }
                        let src_path = std::path::Path::new(audio_src);
                        if let Some(file_name) = src_path.file_name() {
                                let dest_path = assets_dir.join(file_name);
                                if let Err(e) = fs::copy(src_path, &dest_path) {
                                        println!("Failed to copy asset: {}", e);
                                }
                                audio_path_str = format!("assets/{}", file_name.to_string_lossy());
                        }
                }

                let content_type = match clip.content {
                        crate::daw::model::ClipContent::Midi => "midi",
                        crate::daw::model::ClipContent::Audio { .. } => "audio",
                };

                let inst_ids_str = clip
                        .instrument_ids
                        .iter()
                        .map(|id| format!("\"{}\"", id))
                        .collect::<Vec<_>>()
                        .join(", ");

                let inst_routes_str = clip
                        .instrument_routes
                        .iter()
                        .map(|(k, v)| format!("[\"{}\"] = {}", k, v))
                        .collect::<Vec<_>>()
                        .join(", ");

                script.push_str(&format!("clip {{\n  id = \"{}\",\n  track_id = {},\n  name = \"{}\",\n  color = \"{}\",\n  start = {},\n  start_bar = {},\n  start_beat = {},\n  start_sixteenth = {},\n  start_tick = {},\n  duration = {},\n  duration_bars = {},\n  duration_beats = {},\n  duration_sixteenths = {},\n  duration_ticks = {},\n  duration_total_ticks = {},\n  type = \"{}\",\n  audio_path = \"{}\",\n  instrument_ids = {{{}}},\n  instrument_routes = {{{}}}\n}}\n\n",
            clip.id, clip.track_id, clip.name, clip.color,
            clip.start.time, clip.start.bar, clip.start.beat, clip.start.sixteenth, clip.start.tick,
            clip.length.seconds, clip.length.bars, clip.length.beats, clip.length.sixteenths, clip.length.ticks, clip.length.total_ticks,
            content_type, audio_path_str, inst_ids_str, inst_routes_str));
        }

        for mixer in mixer_tracks {
                script.push_str(&format!("mixer_strip {{\n  id = {},\n  volume = {:.2},\n  pan = {:.2},\n  mute = {},\n  solo = {}\n}}\n\n",
            mixer.id, mixer.volume, mixer.pan, mixer.mute, mixer.solo));
        }

        script
}
